version: '3.8'

services:
  ocr-service:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app
      - ./uploads:/usr/src/app/uploads
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: ocr-redis
    ports:
      - "6379:6379"
